module Sound.Rhythm.Generate where

import Sound.Rhythm.LSystem (generateTree)

---------------------------------------------------------------------
-- These function are used to create new patterns
---------------------------------------------------------------------

-- Replicate the list and add it to patternMMap
newReplPattern :: [[Double]] ->  [Double]
newReplPattern ls = concat ls


--newSimilarPattern :: [[Double]] -> Double -> Int -> [[Double]]
--newSimilarPattern xs beat' len = do


---------------------------------------------------------------------
-- Used to create the pattern which is generated by L-System
-- arg symbol means the base pattern.
-- arg rule means the rule of L-System
-- arg initial means the initial value of L-System
-- arg n means the dimension used to create L-System tree.
-- arg len means the length of the list user wanted.
---------------------------------------------------------------------

newLPattern :: ([Double], [Double]) -> String -> String -> Int -> Int -> [Double]
newLPattern symbol rule initial n len = take len $ generateTree symbol rule initial n
