name:                fluere-base
version:             0.1.0.0
github:              "rystylee/fluere-base"
license:             BSD3
author:              "rystylee"
maintainer:          "rystylee8@gmail.com"
copyright:           "Copyright (c) 2018 rystylee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rystylee/fluere-base#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: .
  dependencies:
  - hosc
  - time
  - stm
  - containers

# executables:
#   fluere-base-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - fluere-base
# 
# tests:
#   fluere-base-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - fluere-base
